version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=sccaeia
      - POSTGRESQL_PASSWORD=sccaeia
      - POSTGRESQL_DATABASE=sccaeia
      - POSTGRESQL_INITDB_ARGS=--timezone=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - POSTGRESQL_TIMEZONE=America/Sao_Paulo
    volumes:
      - postgres_pg_data:/bitnami/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_pg_data:
